// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: internal_message.capnp

#ifndef CAPNP_INCLUDED_bf4ddef67d0e61e6_
#define CAPNP_INCLUDED_bf4ddef67d0e61e6_

#include <capnp/generated-header-support.h>

#if CAPNP_VERSION != 5003
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(9532ea162ee61fa5);
CAPNP_DECLARE_SCHEMA(c618e02d470e38c7);
enum class MessageType_c618e02d470e38c7: uint16_t {
  SEND,
  ECHO_MESSAGE,
  READY,
};
CAPNP_DECLARE_ENUM(MessageType, c618e02d470e38c7);

}  // namespace schemas
}  // namespace capnp


struct InternalMessage {
  InternalMessage() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  typedef ::capnp::schemas::MessageType_c618e02d470e38c7 MessageType;


  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(9532ea162ee61fa5, 5, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand = &schema->defaultBrand;
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class InternalMessage::Reader {
public:
  typedef InternalMessage Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand);
  }
#endif  // !CAPNP_LITE

  inline  ::uint64_t getClientId() const;

  inline  ::uint64_t getNonce() const;

  inline  ::uint64_t getMchainHash() const;

  inline bool hasMessage() const;
  inline  ::capnp::Data::Reader getMessage() const;

  inline  ::uint64_t getNodeId() const;

  inline  ::InternalMessage::MessageType getType() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class InternalMessage::Builder {
public:
  typedef InternalMessage Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::uint64_t getClientId();
  inline void setClientId( ::uint64_t value);

  inline  ::uint64_t getNonce();
  inline void setNonce( ::uint64_t value);

  inline  ::uint64_t getMchainHash();
  inline void setMchainHash( ::uint64_t value);

  inline bool hasMessage();
  inline  ::capnp::Data::Builder getMessage();
  inline void setMessage( ::capnp::Data::Reader value);
  inline  ::capnp::Data::Builder initMessage(unsigned int size);
  inline void adoptMessage(::capnp::Orphan< ::capnp::Data>&& value);
  inline ::capnp::Orphan< ::capnp::Data> disownMessage();

  inline  ::uint64_t getNodeId();
  inline void setNodeId( ::uint64_t value);

  inline  ::InternalMessage::MessageType getType();
  inline void setType( ::InternalMessage::MessageType value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class InternalMessage::Pipeline {
public:
  typedef InternalMessage Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline  ::uint64_t InternalMessage::Reader::getClientId() const {
  return _reader.getDataField< ::uint64_t>(
      0 * ::capnp::ELEMENTS);
}

inline  ::uint64_t InternalMessage::Builder::getClientId() {
  return _builder.getDataField< ::uint64_t>(
      0 * ::capnp::ELEMENTS);
}
inline void InternalMessage::Builder::setClientId( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      0 * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t InternalMessage::Reader::getNonce() const {
  return _reader.getDataField< ::uint64_t>(
      1 * ::capnp::ELEMENTS);
}

inline  ::uint64_t InternalMessage::Builder::getNonce() {
  return _builder.getDataField< ::uint64_t>(
      1 * ::capnp::ELEMENTS);
}
inline void InternalMessage::Builder::setNonce( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      1 * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t InternalMessage::Reader::getMchainHash() const {
  return _reader.getDataField< ::uint64_t>(
      2 * ::capnp::ELEMENTS);
}

inline  ::uint64_t InternalMessage::Builder::getMchainHash() {
  return _builder.getDataField< ::uint64_t>(
      2 * ::capnp::ELEMENTS);
}
inline void InternalMessage::Builder::setMchainHash( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      2 * ::capnp::ELEMENTS, value);
}

inline bool InternalMessage::Reader::hasMessage() const {
  return !_reader.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline bool InternalMessage::Builder::hasMessage() {
  return !_builder.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Data::Reader InternalMessage::Reader::getMessage() const {
  return ::capnp::_::PointerHelpers< ::capnp::Data>::get(
      _reader.getPointerField(0 * ::capnp::POINTERS));
}
inline  ::capnp::Data::Builder InternalMessage::Builder::getMessage() {
  return ::capnp::_::PointerHelpers< ::capnp::Data>::get(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}
inline void InternalMessage::Builder::setMessage( ::capnp::Data::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Data>::set(
      _builder.getPointerField(0 * ::capnp::POINTERS), value);
}
inline  ::capnp::Data::Builder InternalMessage::Builder::initMessage(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Data>::init(
      _builder.getPointerField(0 * ::capnp::POINTERS), size);
}
inline void InternalMessage::Builder::adoptMessage(
    ::capnp::Orphan< ::capnp::Data>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Data>::adopt(
      _builder.getPointerField(0 * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Data> InternalMessage::Builder::disownMessage() {
  return ::capnp::_::PointerHelpers< ::capnp::Data>::disown(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}

inline  ::uint64_t InternalMessage::Reader::getNodeId() const {
  return _reader.getDataField< ::uint64_t>(
      3 * ::capnp::ELEMENTS);
}

inline  ::uint64_t InternalMessage::Builder::getNodeId() {
  return _builder.getDataField< ::uint64_t>(
      3 * ::capnp::ELEMENTS);
}
inline void InternalMessage::Builder::setNodeId( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      3 * ::capnp::ELEMENTS, value);
}

inline  ::InternalMessage::MessageType InternalMessage::Reader::getType() const {
  return _reader.getDataField< ::InternalMessage::MessageType>(
      16 * ::capnp::ELEMENTS);
}

inline  ::InternalMessage::MessageType InternalMessage::Builder::getType() {
  return _builder.getDataField< ::InternalMessage::MessageType>(
      16 * ::capnp::ELEMENTS);
}
inline void InternalMessage::Builder::setType( ::InternalMessage::MessageType value) {
  _builder.setDataField< ::InternalMessage::MessageType>(
      16 * ::capnp::ELEMENTS, value);
}


#endif  // CAPNP_INCLUDED_bf4ddef67d0e61e6_
