version: '3'
services:

  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - "6378:6379"
#    volumes:
#      - ../data/redis:/data
    restart: always

  redis-commander:
    container_name: redis_commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6378
    ports:
    - 8081:8081